name = "article-consumer"
main = "src/index.ts"
compatibility_date = "2023-03-12"

[[ queues.consumers ]]
queue = "article-queue" 
max_batch_size = 10
max_batch_timeout = 5

[[ d1_databases ]]
binding = "DB"
database_name = "article-db"
database_id = "xxxxxxxxxxxxxxx"